//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZazaInc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrevista
    {
        public int id_Entrevista { get; set; }
        public int Id_usuario { get; set; }
        public int Id_solicitante { get; set; }
        public string notas { get; set; }
        public Nullable<int> departamento_deseado { get; set; }
        public string estado { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Solicitante Solicitante { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
