//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZazaInc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitante()
        {
            this.Entrevistas = new HashSet<Entrevista>();
        }
    
        public int id_Solicitante { get; set; }
        public string nombre_Solicitante { get; set; }
        public string apellido_Solicitante { get; set; }
        public int cedula_Solicitante { get; set; }
        public string correo_Solicitante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrevista> Entrevistas { get; set; }
    }
}
