//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZazaInc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacacione
    {
        public int id_vacaciones { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_final { get; set; }
        public int id_usuario { get; set; }
        public int id_empleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
